### ISSUE TITLE
From 2.3.4 to 2.3.5 - NoClassDefFoundError: org/modelmapper/builder/ConfigurableMapExpression

### ISSUE THREAD

**Issue by MichelePollini** [modelmapper/modelmapper#510]
Hi! I have a compatibility issue when I upgrade modelmapper version to 2.3.5.

Caused by: java.lang.NoClassDefFoundError: org/modelmapper/builder/ConfigurableMapExpression

`typeMap.addMappings(mapper -> mapper.skip(DestSetter));`

I didn't expect a backward compatibility issue caused by a minor upgrade. How can i fix it? Thank you

**Comment by chhsiao90** [comment]
Hi @MichelePollini ,

I guessed there is no breaking change during the minor upgrade. Can you provide more detail (maybe reproducible code) so we can identify the issue? Thanks.
